version: '3.3'
services:
  ml-actions-ubuntu:
    image: ml-actions/ubuntu:latest
    build:
      context: .
    container_name: ml-actions-ubuntu
    environment:
      - HTTP_PROXY
      - HTTPS_PROXY
    stdin_open: true
    tty: true
    # stdin_open and tty correspond to -it in docker run
    volumes:
      - .:/target

#    volumes:
#      - ./local-dir:/container-dir
#    restart: always
#    ports:
#    - "3128:3128"

# Usage
# See README