name: Node.js CI

on: [push]

jobs:
 
        
  ci:
    # See here for details of available tools, e.g. cli 
    # https://help.github.com/en/actions/automating-your-workflow-with-github-actions/software-installed-on-github-hosted-runners#ubuntu-1804-lts
    runs-on: ubuntu-latest
    env:
      ENV_CI: true
      JOB_SCOPED_ENV_VAR_1: job_scoped_env_val_1
      JOB_SCOPED_ENV_VAR_2: job_scoped_env_val_2
      MY_ENV: DEV
      SAML2_AWS_MIN_SESSION_DURATION: 1000

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup node env
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'

      - name: saml2aws install
        run: make saml2aws-install

      ## Example of using configure (not, with dummy values only here!!)
      - name: saml2aws configure
        run: |
          make saml2aws-configure IDP_URL="${{ secrets.IDP_URL }}" USERNAME="${{ secrets.USERNAME }}"
          cat ~/.saml2aws

      ## Example of using logging in, using saml2aws (again, dummy only)
      - name: saml2aws login
        run: |
          echo example command
          echo make saml2aws-login PASS=BLAHBLAH

      # https://help.github.com/en/actions/automating-your-workflow-with-github-actions/contexts-and-expression-syntax-for-github-actions
      # nb: Be careful, context can contain github.token, (nb: it will be masked if dumped to the screen)
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
           
      # Using conditions / variables
      # Set an env var https://help.github.com/en/actions/automating-your-workflow-with-github-actions/development-tools-for-github-actions#set-an-environment-variable-set-env
      # e.g. github.ref = refs/heads/master
      # 
      - name: Set env to prod
        if: endsWith(github.ref, '/master')
        run: |
          echo "::set-env name=MY_ENV::PROD"

      - name: Dump env vars
        run: make dump
        
      - name: envsubst version check
        run: envsubst --version

      - name: Install
        run: make reinstall

      # # See https://medium.com/henngeblog/github-actions-in-action-528d205da316
      - name: SAM Install
        run: |
           echo PATH=$PATH
           make sam-install
           echo "::add-path::$HOME/.local/bin"

     
      - name: SAM Details
        run: |
           echo PATH=$PATH
           sam --version

      - uses: actions/cache@v1
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Quality
        env:
          STEP_SCOPED_ENV_VAR_1: step_scoped_env_val_1
          STEP_SCOPED_ENV_VAR_2: step_scoped_env_val_2
        run: make code-quality

      - name: Test
        run: make test
        

  cd:
    runs-on: ubuntu-latest
    needs: [ci]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup node env
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
     
      - name: Deploy API
        run: make deploy-api

      - name: Deploy UI
        run: make deploy-ui

      - name: Test - Infra
        run: make infra-test

      - name: Test - Acceptance
        run: make acceptance-test


