name: Node.js CI

on: [push]

jobs:
  ci:
    runs-on: ubuntu-latest
    env:
      ENV_CI: true
      JOB_SCOPED_ENV_VAR_1: job_scoped_env_val_1
      JOB_SCOPED_ENV_VAR_2: job_scoped_env_val_2
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup node env
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'

      - name: Install
        run: make reinstall

      - uses: actions/cache@v1
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Quality
        env:
          STEP_SCOPED_ENV_VAR_1: step_scoped_env_val_1
          STEP_SCOPED_ENV_VAR_2: step_scoped_env_val_2
        run: make code-quality

      - name: Test
        run: make test

      - name: Deploy API
        run: make deploy-api

      - name: Deploy UI
        run: make deploy-ui

      - name: Test - Infra
        run: make infra-test

      - name: Test - Acceptance
        run: make acceptance-test



