name: Node.js CI

on: [push]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup node env
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'

      - name: Install
        run: npm install

      - name: Clean
        run: make clean

      - name: Quality
        env:
          ENV_VAR_1: env_val_1
          ENV_VAR_2: env_val_2
        run: make code-quality

      - name: Test
        run: make test


